galaxy_info:
  author: Jean-Michel Chantrein
  description: "Sandbox sécurisé pour exécution de code"
  min_ansible_version: "2.16"
  license: MIT
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
dependencies: []
