---
extends: default

rules:
  line-length:
    max: 120
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore:
  - .claude/
  - .venv/
  - node_modules/
