---
# site.yml — Master playbook for AnKLuMe infrastructure
#
# Three-phase architecture (ADR-006):
#
# Phase 1 — Infrastructure (tag: infra):
#   - hosts: all, connection: local
#   - Drives Incus via CLI on the controller (anklume-instance)
#   - Creates projects, networks, profiles, instances
#   - See ADR-015 in docs/ARCHITECTURE.md
#
# Phase 2 — Provisioning (tag: provision):
#   - hosts: all, connection: community.general.incus
#   - Connects INTO instances via `incus exec`
#   - Installs packages, configures locale, timezone, services
#   - admin_bootstrap applied only to the admin group (ADR-019)
#
# Phase 3 — Network isolation (tag: nftables):
#   - hosts: localhost, connection: local
#   - Generates nftables inter-bridge isolation rules
#   - Deploy on host with: make nftables-deploy
#
# Concurrency note:
#   With forks > 1, multiple hosts may attempt to create the same resource
#   simultaneously. The reconciliation pattern handles this gracefully in
#   most cases. If strict sequential execution is needed, uncomment the
#   serial: 1 line below.
#
# Usage:
#   make apply                      # Full infrastructure + provisioning
#   make apply-infra                # Infrastructure only (--tags infra)
#   make apply-provision            # Provisioning only (--tags provision)
#   make apply-base                 # Base system only (--tags base)
#   make apply-limit G=<domain>     # Single domain (--limit <domain>)
#   make check                      # Dry-run (--check --diff)
#   make nftables                   # Generate nftables isolation rules
#   make nftables-deploy            # Deploy rules on host (run FROM host)

- name: "Infrastructure | Reconcile Incus resources"
  hosts: all
  connection: local
  gather_facts: false
  serial: 1  # Sequential execution — prevents race conditions on shared Incus resources
  tags:
    - infra

  tasks:
    - name: Infrastructure | Apply incus_projects
      ansible.builtin.include_role:
        name: incus_projects
        apply:
          tags:
            - projects
            - infra
      tags:
        - projects
        - infra

    - name: Infrastructure | Apply incus_networks
      ansible.builtin.include_role:
        name: incus_networks
        apply:
          tags:
            - networks
            - infra
      tags:
        - networks
        - infra

    - name: Infrastructure | Apply incus_profiles
      ansible.builtin.include_role:
        name: incus_profiles
        apply:
          tags:
            - profiles
            - infra
      tags:
        - profiles
        - infra

    - name: Infrastructure | Apply incus_images
      ansible.builtin.include_role:
        name: incus_images
        apply:
          tags:
            - images
            - infra
      run_once: true
      tags:
        - images
        - infra

    - name: Infrastructure | Apply incus_instances
      ansible.builtin.include_role:
        name: incus_instances
        apply:
          tags:
            - instances
            - infra
      tags:
        - instances
        - infra

    - name: Infrastructure | Apply incus_firewall_vm
      ansible.builtin.include_role:
        name: incus_firewall_vm
        apply:
          tags:
            - firewall
            - infra
      when: "'firewall_router' in (instance_roles | default([]))"
      run_once: true
      tags:
        - firewall
        - infra

# ── Phase 2: Provisioning ──────────────────────────────────
# Connects INTO instances via the community.general.incus plugin
# (uses `incus exec` under the hood — no SSH needed).
#
# ansible_host is overridden to inventory_hostname because the PSOT
# generator sets ansible_host to the instance IP (useful for networking),
# but the Incus connection plugin needs the container name.

- name: "Provisioning | Configure instances"
  hosts: all
  gather_facts: false
  # serial: 1  # Uncomment for strict sequential provisioning
  tags:
    - provision
  vars:
    ansible_connection: community.general.incus
    ansible_user: root
    ansible_incus_project: "{{ incus_project }}"
    ansible_host: "{{ inventory_hostname }}"
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Provisioning | Bootstrap Python on target
      ansible.builtin.raw: |
        test -x /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      changed_when: false
      tags:
        - always

    - name: Provisioning | Gather facts after Python bootstrap
      ansible.builtin.setup:
      tags:
        - always

  tasks:
    - name: Provisioning | Apply base_system
      ansible.builtin.include_role:
        name: base_system
        apply:
          tags:
            - base
            - provision
      tags:
        - base
        - provision

    - name: Provisioning | Apply admin_bootstrap
      ansible.builtin.include_role:
        name: admin_bootstrap
        apply:
          tags:
            - admin
            - provision
      when: "'anklume' in group_names"
      tags:
        - admin
        - provision

    - name: Provisioning | Apply ollama_server
      ansible.builtin.include_role:
        name: ollama_server
        apply:
          tags:
            - llm
            - ollama
            - provision
      when: "'ollama_server' in (instance_roles | default([]))"
      tags:
        - llm
        - ollama
        - provision

    - name: Provisioning | Apply open_webui
      ansible.builtin.include_role:
        name: open_webui
        apply:
          tags:
            - llm
            - webui
            - provision
      when: "'open_webui' in (instance_roles | default([]))"
      tags:
        - llm
        - webui
        - provision

    - name: Provisioning | Apply stt_server
      ansible.builtin.include_role:
        name: stt_server
        apply:
          tags:
            - stt
            - provision
      when: "'stt_server' in (instance_roles | default([]))"
      tags:
        - stt
        - provision

    - name: Provisioning | Apply lobechat
      ansible.builtin.include_role:
        name: lobechat
        apply:
          tags:
            - lobechat
            - provision
      when: "'lobechat' in (instance_roles | default([]))"
      tags:
        - lobechat
        - provision

    - name: Provisioning | Apply opencode_server
      ansible.builtin.include_role:
        name: opencode_server
        apply:
          tags:
            - opencode
            - provision
      when: "'opencode_server' in (instance_roles | default([]))"
      tags:
        - opencode
        - provision

    - name: Provisioning | Apply code_sandbox
      ansible.builtin.include_role:
        name: code_sandbox
        apply:
          tags:
            - code_sandbox
            - provision
      when: "'code_sandbox' in (instance_roles | default([]))"
      tags:
        - code_sandbox
        - provision

    - name: Provisioning | Apply firewall_router
      ansible.builtin.include_role:
        name: firewall_router
        apply:
          tags:
            - firewall
            - provision
      when: "'firewall_router' in (instance_roles | default([]))"
      tags:
        - firewall
        - provision

# ── Phase 3: Network isolation ───────────────────────────────
# Generates nftables rules to isolate non-admin bridges.
# Rules are generated inside the admin container; deploy on
# the host with: make nftables-deploy

- name: "Firewall | Generate inter-bridge isolation rules"
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - nftables
  roles:
    - role: incus_nftables
