---
driver:
  name: default
platforms:
  - name: molecule-code-sandbox
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    host_vars:
      molecule-code-sandbox:
        ansible_connection: community.general.incus
verifier:
  name: ansible
