---
driver:
  name: default
platforms:
  - name: molecule-lobechat
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    host_vars:
      molecule-lobechat:
        ansible_connection: community.general.incus
verifier:
  name: ansible
