galaxy_info:
  author: Jean-Michel Chantrein
  description: "Outils de développement basiques (build-essential, git, python3)"
  min_ansible_version: "2.16"
  license: MIT
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
dependencies: []
