galaxy_info:
  author: Jean-Michel Chantrein
  description: "VM de tests E2E (Incus, nftables, uv)"
  min_ansible_version: "2.16"
  license: MIT
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
dependencies: []
