#!/usr/bin/env bash
# apply.sh — Apply domain-based Sway/i3 configuration
# Reads JSON config from stdin, generates and applies Sway config snippets.
#
# Usage:
#   echo '{"domains":[...]}' | ./apply.sh
#   ./apply.sh --reset
#   echo '{"domains":[...]}' | ./apply.sh --dry-run

set -euo pipefail

SWAY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
ANKLUME_SNIPPET="$SWAY_CONFIG_DIR/anklume-domains.conf"

info()  { echo -e "\033[0;34m[INFO]\033[0m $*"; }
ok()    { echo -e "\033[0;32m[ OK ]\033[0m $*"; }
warn()  { echo -e "\033[1;33m[WARN]\033[0m $*"; }
err()   { echo -e "\033[0;31m[ERR ]\033[0m $*" >&2; }

# ── Reset mode ──
if [ "${1:-}" = "--reset" ]; then
    if [ -f "$ANKLUME_SNIPPET" ]; then
        rm -f "$ANKLUME_SNIPPET"
        ok "Removed anklume domain snippet"
        # Remove include from main config
        if [ -f "$SWAY_CONFIG_DIR/config" ]; then
            sed -i '/include.*anklume-domains\.conf/d' "$SWAY_CONFIG_DIR/config"
            ok "Removed include from sway config"
        fi
        swaymsg reload 2>/dev/null || true
    else
        info "No anklume snippet to remove"
    fi
    exit 0
fi

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=true
fi

# ── Read JSON config from stdin ──
if [ -t 0 ] && [ "$DRY_RUN" = false ]; then
    err "No config provided on stdin"
    echo "Usage: echo '{\"domains\":[...]}' | $0" >&2
    exit 1
fi

CONFIG=$(cat)

# ── Parse with Python (jq alternative) ──
SNIPPET=$(python3 - "$CONFIG" <<'PYEOF'
import json
import sys

config = json.loads(sys.argv[1])
domains = config.get("domains", [])
virtual_desktops = config.get("virtual_desktops", "auto")
window_borders = config.get("window_borders", "trust_level")

lines = [
    "# anklume domain desktop configuration",
    "# Generated by plugins/desktop/sway/apply.sh",
    "# Do not edit — regenerated by make desktop-apply",
    "",
    "# Enable window borders",
    "default_border pixel 3",
    "",
]

# Virtual desktop (workspace) assignments
if virtual_desktops == "auto" and domains:
    lines.append("# Virtual desktops — one per domain")
    for i, domain in enumerate(domains, 1):
        name = domain.get("name", f"domain-{i}")
        lines.append(f'set $ws_{name} "{i}: {name}"')
    lines.append("")

    # Keybindings for workspace switching
    for i, domain in enumerate(domains, 1):
        name = domain.get("name", f"domain-{i}")
        lines.append(f"bindsym $mod+{i} workspace $ws_{name}")
        lines.append(f"bindsym $mod+Shift+{i} move container to workspace $ws_{name}")
    lines.append("")

# Window border colors per domain
if window_borders == "trust_level":
    lines.append("# Domain-colored window borders (QubesOS-style)")
    for domain in domains:
        name = domain.get("name", "unknown")
        color = domain.get("color", "#888888")
        for machine in domain.get("machines", []):
            lines.append(
                f'for_window [title=".*{machine}.*"] '
                f"client.focused {color} {color} #ffffff {color}"
            )
    lines.append("")

print("\n".join(lines))
PYEOF
)

if [ "$DRY_RUN" = true ]; then
    echo "$SNIPPET"
    exit 0
fi

# ── Apply ──
mkdir -p "$SWAY_CONFIG_DIR"

# Write snippet
echo "$SNIPPET" > "$ANKLUME_SNIPPET"
ok "Generated $ANKLUME_SNIPPET"

# Ensure include in main config
if [ -f "$SWAY_CONFIG_DIR/config" ]; then
    if ! grep -q "anklume-domains.conf" "$SWAY_CONFIG_DIR/config"; then
        echo "" >> "$SWAY_CONFIG_DIR/config"
        echo "# anklume domain integration" >> "$SWAY_CONFIG_DIR/config"
        echo "include anklume-domains.conf" >> "$SWAY_CONFIG_DIR/config"
        ok "Added include to sway config"
    fi
fi

# Reload if Sway is running
if [ -n "${SWAYSOCK:-}" ]; then
    swaymsg reload 2>/dev/null && ok "Sway config reloaded" || warn "Could not reload Sway"
fi
