#!/usr/bin/env python3
"""Generate desktop environment configuration from infra.yml.

Reads domain trust levels and generates integration snippets for:
- Sway/i3: window rules with domain-colored borders
- foot terminal: domain-colored profiles
- .desktop files: quick-launch entries per instance

Usage:
    scripts/desktop-config.py --sway       # Sway/i3 config rules
    scripts/desktop-config.py --foot       # foot terminal profiles
    scripts/desktop-config.py --desktop    # .desktop entry files
    scripts/desktop-config.py --all        # Generate everything

Phase 21: Desktop Integration
"""

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate import load_infra  # noqa: E402

# ── Color mappings ───────────────────────────────────────────────

# Trust level → hex color for borders (bright, visible)
TRUST_BORDER_COLORS = {
    "admin": "#3333ff",
    "trusted": "#33cc33",
    "semi-trusted": "#cccc33",
    "untrusted": "#cc3333",
    "disposable": "#cc33cc",
}

# Trust level → hex color for terminal backgrounds (dark, readable)
TRUST_BG_COLORS = {
    "admin": "#0a0a2a",
    "trusted": "#0a1a0a",
    "semi-trusted": "#1a1a0a",
    "untrusted": "#1a0a0a",
    "disposable": "#1a0a1a",
}

# Trust level → tmux 256-color (matching console.py)
TRUST_TMUX_COLORS = {
    "admin": "colour17",
    "trusted": "colour22",
    "semi-trusted": "colour58",
    "untrusted": "colour52",
    "disposable": "colour53",
}


def infer_trust_level(domain_name, domain_config):
    """Infer trust level (same logic as console.py)."""
    trust = domain_config.get("trust_level")
    if trust:
        return trust
    if "admin" in domain_name.lower():
        return "admin"
    if domain_config.get("ephemeral", False):
        return "disposable"
    return "trusted"


def gather_domains(infra):
    """Extract domain info from infra dict."""
    domains = []
    for dname in sorted(infra.get("domains", {}).keys()):
        dconfig = infra["domains"][dname]
        trust = infer_trust_level(dname, dconfig)
        machines = list(dconfig.get("machines", {}).keys())
        domains.append({
            "name": dname,
            "trust_level": trust,
            "machines": machines,
            "border_color": TRUST_BORDER_COLORS.get(trust, "#888888"),
            "bg_color": TRUST_BG_COLORS.get(trust, "#1a1a1a"),
        })
    return domains


# ── Sway/i3 config ──────────────────────────────────────────────

def generate_sway_config(domains):
    """Generate Sway/i3 window rules for domain-colored borders."""
    lines = [
        "# AnKLuMe domain-colored window borders",
        "# Generated by scripts/desktop-config.py",
        "# Add to ~/.config/sway/config or ~/.config/i3/config",
        "",
        "# Enable window borders",
        "default_border pixel 3",
        "",
    ]

    for d in domains:
        color = d["border_color"]
        lines.append(f"# Domain: {d['name']} (trust: {d['trust_level']})")
        # Match by window title pattern [domain]
        lines.append(
            f'for_window [title="^\\[{d["name"]}\\]"] '
            f"border pixel 3"
        )
        lines.append(
            f'for_window [title="^\\[{d["name"]}\\]"] '
            f'client.focused {color} {color} #ffffff {color}'
        )
        # Match by app_id pattern (set by domain-exec.sh --terminal)
        lines.append(
            f'for_window [app_id="^anklume-{d["name"]}"] '
            f"border pixel 3"
        )
        lines.append("")

    lines.append("# Keybindings for quick domain access")
    lines.append("# Customize the modifier and keys as needed")
    for i, d in enumerate(domains[:9]):
        lines.append(
            f"# $mod+F{i + 1}: open terminal to {d['name']}"
        )
        if d["machines"]:
            lines.append(
                f'# bindsym $mod+F{i + 1} exec '
                f'scripts/domain-exec.sh {d["machines"][0]} --terminal'
            )

    return "\n".join(lines)


# ── foot terminal profiles ───────────────────────────────────────

def generate_foot_config(domains):
    """Generate foot terminal color profiles for each domain."""
    lines = [
        "# AnKLuMe domain color profiles for foot terminal",
        "# Generated by scripts/desktop-config.py",
        "# Merge into ~/.config/foot/foot.ini or use foot --override",
        "",
    ]

    for d in domains:
        lines.append(f"# Domain: {d['name']} (trust: {d['trust_level']})")
        lines.append(f"# Usage: foot --override 'colors.background={d['bg_color']}'")
        lines.append(f"# Or: scripts/domain-exec.sh {d['machines'][0] if d['machines'] else 'INSTANCE'} --terminal")
        lines.append("")

    lines.append("# Profiles (add to foot.ini under respective sections):")
    lines.append("")
    for d in domains:
        lines.append(f"# [{d['name']}]")
        lines.append(f"# background={d['bg_color']}")
        lines.append("")

    return "\n".join(lines)


# ── Desktop entries ──────────────────────────────────────────────

def generate_desktop_entries(domains, output_dir):
    """Generate .desktop files for each instance."""
    os.makedirs(output_dir, exist_ok=True)
    generated = []

    for d in domains:
        for machine in d["machines"]:
            filename = f"anklume-{machine}.desktop"
            filepath = os.path.join(output_dir, filename)

            entry = (
                "[Desktop Entry]\n"
                f"Name=[{d['name']}] {machine}\n"
                f"Comment=AnKLuMe {d['name']} domain — {d['trust_level']}\n"
                f"Exec=scripts/domain-exec.sh {machine} --terminal\n"
                "Terminal=false\n"
                "Type=Application\n"
                "Categories=System;\n"
                f"StartupWMClass=anklume-{d['name']}\n"
                f"Keywords=anklume;incus;{d['name']};{machine}\n"
            )
            with open(filepath, "w") as f:
                f.write(entry)
            generated.append(filepath)

    return generated


# ── Main ─────────────────────────────────────────────────────────

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate desktop environment config from infra.yml"
    )
    parser.add_argument(
        "infra_file", nargs="?",
        help="Path to infra.yml or infra/ directory (default: auto-detect)",
    )
    parser.add_argument("--sway", action="store_true", help="Generate Sway/i3 config")
    parser.add_argument("--foot", action="store_true", help="Generate foot terminal profiles")
    parser.add_argument("--desktop", action="store_true", help="Generate .desktop entry files")
    parser.add_argument("--all", action="store_true", help="Generate all configurations")
    parser.add_argument(
        "--output-dir", default="desktop",
        help="Output directory for generated files (default: desktop/)",
    )

    args = parser.parse_args(argv)

    # Auto-detect infra file
    if args.infra_file is None:
        if Path("infra").is_dir():
            args.infra_file = "infra"
        elif Path("infra.yml").is_file():
            args.infra_file = "infra.yml"
        else:
            print("ERROR: Could not find infra.yml or infra/", file=sys.stderr)
            sys.exit(1)

    infra = load_infra(args.infra_file)
    domains = gather_domains(infra)

    if not domains:
        print("No domains found in infra.yml")
        return

    if not any([args.sway, args.foot, args.desktop, args.all]):
        args.all = True

    os.makedirs(args.output_dir, exist_ok=True)

    if args.sway or args.all:
        config = generate_sway_config(domains)
        path = os.path.join(args.output_dir, "sway-anklume.conf")
        with open(path, "w") as f:
            f.write(config)
        print(f"  Sway config:    {path}")

    if args.foot or args.all:
        config = generate_foot_config(domains)
        path = os.path.join(args.output_dir, "foot-anklume.ini")
        with open(path, "w") as f:
            f.write(config)
        print(f"  foot profiles:  {path}")

    if args.desktop or args.all:
        entries = generate_desktop_entries(domains, args.output_dir)
        for e in entries:
            print(f"  Desktop entry:  {e}")

    print(f"\nGenerated {len(domains)} domain configs in {args.output_dir}/")
    print("Copy Sway config to ~/.config/sway/config.d/anklume.conf")
    print("Copy .desktop files to ~/.local/share/applications/")


if __name__ == "__main__":
    main()
