---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Vérifier que curl est installé
      ansible.builtin.command:
        cmd: which curl
      changed_when: false

    - name: Vérifier que sudo est installé
      ansible.builtin.command:
        cmd: which sudo
      changed_when: false

    - name: Vérifier que le paquet locales est installé
      ansible.builtin.command:
        cmd: dpkg -s locales
      changed_when: false
